P23517082023/P23517082023/Models/Group.cs
namespace P23517082023.Models
{
    public class Group
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int Count { get; set; }
        public string EducationType { get; set; }
    }
}

P23517082023/P23517082023/Models/Student.cs
namespace P23517082023.Models
{
    public class Student
    {
        public int Id { get; set; }
        public int GroupId { get; set; }
        public string Name { get; set; }
        public string SurName { get; set; }
        public int  Age { get; set; }
    }
}

P23517082023/P23517082023/ViewModels/HomeVMs/IndexVM.cs
using P23517082023.Models;

namespace P23517082023.ViewModels.HomeVMs
{
    public class IndexVM
    {
        public Student Student { get; set; }
        public Group Group { get; set; }
        public int A { get; set; }
    }
}

P23517082023/P23517082023/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using P23517082023.Models;
using P23517082023.ViewModels.HomeVMs;

namespace P23517082023.Controllers
{
    public class HomeController : Controller
    {
        private readonly List<Group> _groups;

        public HomeController()
        {
            _groups = new List<Group>
            {
                new Group {Id = 1,Name = "P235",Count=16,EducationType="Back End"},
                new Group {Id = 2,Name = "P234",Count=16,EducationType="Front End"},
                new Group {Id = 3,Name = "229",Count=16,EducationType="Bitib"},
                new Group {Id = 4,Name = "P138",Count=16,EducationType="Sabah Teqdimatdi"},
            };
        }

        public IActionResult Index() 
        { 

            return View(_groups); 
        }

        public IActionResult Detail(int? id)
        {
            if (id == null) return BadRequest("Group Id Mutleq Gonderilmelidi");

            if (!_groups.Exists(g => g.Id == id)) return NotFound("Gonderilen Id Yanlisdir");

            Group group = _groups.Find(g => g.Id == id);

            return View(group);
        }

        #region Comment
        //public IActionResult Index()
        //{
        //    //ViewData["name"] = "Hamid";
        //    //ViewBag.Age = 15;

        //    //int a = 10;

        //    //a = 20;

        //    //TempData["name"] = "Mammadov";

        //    //return RedirectToAction(nameof(Detail));

        //    //Group group = new Group();
        //    //group.Name = "P235";
        //    //group.Count = 16;
        //    //group.EducationType = "Back End";

        //    //Student student = new Student();
        //    //student.Name = "Hamid";
        //    //student.SurName = "Mammadov";
        //    //student.Age = 33;

        //    //ViewBag.stu = student;
        //    //ViewBag.group = group;

        //    //IndexVM indexVM = new IndexVM();
        //    //indexVM.Student = student;
        //    //indexVM.Group = group;
        //    //indexVM.A = a;

        //    //return View(indexVM);
        //}
        #endregion
    }
}

P23517082023/P23517082023/Controllers/StudnetController.cs
using Microsoft.AspNetCore.Mvc;
using P23517082023.Models;

namespace P23517082023.Controllers
{
    public class StudnetController : Controller
    {
        private readonly List<Student> _students;

        public StudnetController()
        {
            _students = new List<Student>
            {
                new Student {Name = "Mustafa",SurName = "Melikov",Age = 16,GroupId = 2,Id = 1 },
                new Student {Name = "Emrah",SurName = "Nesirov",Age = 23,GroupId = 2,Id = 2 },
                new Student {Name = "Ehmed",SurName = "Mehdiyev",Age = 23,GroupId = 2,Id = 3 },
                new Student {Name = "Nesrin",SurName = "Esedli",Age = 16,GroupId = 2,Id = 4 },
                new Student {Name = "Murad",SurName = "Eliyev",Age = 20,GroupId = 1,Id = 5 },
                new Student {Name = "Aykhan",SurName = "Quliyev",Age = 9999,GroupId = 1,Id = 6 },
                new Student {Name = "Nicat",SurName = "Misirxanli",Age = 1000,GroupId = 1,Id = 7 },
                new Student {Name = "Mahmud",SurName = "Eliyev",Age = 21,GroupId =3,Id = 8 },
            };
        }

        public IActionResult Index(int? id)
        {
            if (id == null)
            {
                return View(_students);
            }
            else
            {
                if (_students.Exists(s=>s.GroupId == id))
                {
                    List<Student> students = _students.FindAll(s=>s.GroupId == id);
                    return View(students);
                }
                else
                {
                    return NotFound($"Gonderilen Group Id = {id} Yanlisdir");
                }
            }
        }

        public IActionResult Detail(int id)
        {
            if (id == null) return BadRequest("Studnet Id Mutleq Gonderilmelidi");

            Student student = _students.Find(s=>s.Id == id);

            if (student == null) return NotFound();

            return View(student);
        }
    }
}

P23517082023/P23517082023/Views/Home/Detail.cshtml
@model Group
@{
    ViewData["Title"] = "Detail";
}

<h1>Detail</h1>
<ul>
    <li>@Model.Id</li>
    <li>@Model.Name</li>
    <li>@Model.Count</li>
    <li>@Model.EducationType</li>
    <a asp-controller="Studnet" asp-action="index" asp-route-id="@Model.Id">
        <li>
            Telebeler
        </li>
    </a>
</ul>
@*<ul>
    <li>ViewData: @ViewBag.Name</li>
    <li>ViewBag: @ViewData["age"]</li>
    <li>TempData: @TempData["Name"]</li>
    <li>Internal View Variable: @ViewBag.Test</li>
</ul>*@

P23517082023/P23517082023/Views/Home/Index.cshtml
@model List<Group>
<ul>
    @foreach (Group group in Model)
    {
        <a asp-controller="Home" asp-action="Detail" asp-route-id="@group.Id">
            <li>@group.Name</li>
        </a>
    }
</ul>





























@*@model IndexVM*@
@*@{
    ViewData["Title"] = "Home Index";


    ViewBag.Test = "P235";
    int a = 10;

}*@

@*@{
    Student student = ViewBag.stu;
    Group group = ViewBag.group;
}*@


@*<h1>Index</h1>
<ul>
    <li>@Model.Student.Name</li>
    <li>@Model.Group.Name</li>
</ul>*@
@*<ul>
    <li>@student.Name</li>
    <li>@group.Name</li>
    <li></li>
</ul>*@

@*<ul>
    <li>@Model.Name</li>
    <li>@Model.SurName</li>
    <li>@Model.Age</li>
</ul>*@
@*<ul>
    <li>ViewData: @ViewBag.Name</li>
    <li>ViewBag: @ViewData["age"]</li>
    <li>TempData: @TempData["surname"]</li>
    <li>Internal View Variable: @a</li>
    <li>Internal View Variable: @ViewBag.Test</li>
</ul>*@